### ISSUE TITLE
Consider renaming AllowEntriesInWebConfigThatDoNotHaveSettingsClasses

### ISSUE THREAD

**Issue by jstangroome** [uglybugger/ConfigInjector#5]
Given that ConfigInjector also reads app.config files and given that .WithAppSettingsReader() allows the reader implementation to be replaced to read a completely different configuration source, perhaps this method should be named more generically, eg:

```
AllowConfigurationEntriesThatDoNotHaveSettingsClasses
```

**Comment by uglybugger** [comment]
Good idea :)  Will do shortly.
